### ISSUE TITLE
Review content of email templates 

### ISSUE THREAD

**Issue by vivanov1410** [connio/emails#15]
### Verify account after signup

![screenshot 2015-08-06 21 33 34](https://cloud.githubusercontent.com/assets/1734413/9128789/f7801ae0-3c82-11e5-9aa0-60668efff645.png)

### Accept invitation of user

![screenshot 2015-08-06 21 35 38](https://cloud.githubusercontent.com/assets/1734413/9128807/21d67cc6-3c83-11e5-86bb-f341cd941296.png)

### Reset user password

![email password reset](https://cloud.githubusercontent.com/assets/1734413/9129226/071f34de-3c8a-11e5-9518-65811cb5d0f4.png)

**Comment by vivanov1410** [comment]
@bmrb can you review text in these three emails and let me know if you want to change anything.

**Comment by bmrb** [comment]
*Verify account after signup*: `Hi Steve, Welcome to Connio!` if name provided. If not provided `Hi there, Welcome to Connio!`.

**Comment by bmrb** [comment]
*Accept invitation of user* ... and left you this **message**.

**Comment by bmrb** [comment]
*Reset user password* looks good.

**Comment by bmrb** [comment]
Couple things:

`app.connio.com/reset` and `app.connio.com/verify` are too generic. Lets have something more contextual like `app.connio.com/resetpwd` and `app.connio.com/userverify`.

There is no button not working warning for Join Team.

**Comment by vivanov1410** [comment]
Links are not decided yet, what you see here is a mock, I will use more descriptive route names like `reset-password` and `verify-email` or something like that.

Also I will add link below button.
